apiVersion: v1
kind: Pod #job,deployment,service
metadata:
 name: myapp-pod
 labels:
   app: myapp
spec:
 containers:
   – name: front-end
     image: nginx
     ports:
       – containerPort: 80
   – name: rss-reader
     image: nickchase/rss-php-nginx:v1
     ports:
       – containerPort: 88

